apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow-system
resources:
- ../../base/crds/
- ../../base/manager/
- ../../base/webhook/
- ../../base/rbac/
- ../../base/runtimes/
- certificate.yaml

images:
  - name: kubeflow/training-operator-v2
    newName: kubeflow/training-operator-v2
    newTag: latest

patchesStrategicMerge: 
  - patch.yaml

vars:
  - name: TRAINER_NAMESPACE
    objref:
      name: trainer-controller-manager
      kind: Service
      apiVersion: v2alpha1
    fieldref:
      fieldpath: metadata.namespace
  - name: TRAINER_SERVICE_NAME
    objref:
      name: trainer-controller-manager
      kind: Service
      apiVersion: v2alpha1
    fieldref:
      fieldpath: metadata.name
  - name: TRAINER_CERT_NAME
    objref:
      name: trainer-webhook-cert
      kind: Certificate
      apiVersion: cert-manager.io/v1
    fieldref:
      fieldpath: metadata.name

configurations:
  - config.yaml

secretGenerator:
  - name: training-operator-v2-webhook-cert
    namespace: kubeflow-system
    options:
      disableNameSuffixHash: true